name: Lint

on:
  push:
    paths:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  check-markdown:
    name: Check Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3
        with:
          files: .
  check-yaml:
    name: Check YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
